[project]
name = "pulse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "plotext>=5.3.2",
    "psutil>=7.1.3",
    "textual>=6.8.0",
    "textual-dev>=1.8.0",
]
