[project]
name = "pulse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psutil>=7.1.3",
    "textual>=6.8.0",
    "textual-plotext>=1.0.1",
]
